% 
% Status : main Dynare file 
% 
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ exedet_ exdet_ recur_ recurs_ 
global options_ endval_
global ys0_ recurs0_ ex0_ ct_
options_ = [];
M_.fname = 'soe1';
% 
% Some global variables initialisation
% 
global_initialization;
diary off;
warning off;

delete soe1.log;
warning on;
warning backtrace;
logname_ = 'soe1.log';
diary 'soe1.log';
erase_compiled_function('soe1_static');
erase_compiled_function('soe1_dynamic');
M_.exo_names = 'RES_RR_US_BAR';
M_.exo_names_tex = '';
M_.exo_names = strvcat(M_.exo_names,'RES_UNR_US_GAP');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'RES_UNR_US_BAR');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'RES_RS_US');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'RES_G_US');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'RES_Y_US');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'RES_LGDP_US_BAR');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'RES_PIE_US');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'RES_UNR_G_US');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'RES_BLT_US');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.exo_names = strvcat(M_.exo_names,'RES_BLT_US_BAR');
M_.exo_names_tex = strvcat(M_.exo_names_tex,'');
M_.endo_names = 'RR_US';
M_.endo_names_tex = '';
M_.endo_names = strvcat(M_.endo_names,'RR_US_BAR');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'UNR_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'UNR_US_GAP');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'UNR_US_BAR');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'PIE_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'PIE_US4');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'Y_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'LGDP_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'LGDP_US_BAR');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'RS_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'G_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'LCPI_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'E4_PIE_US4');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'E1_Y_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'E1_PIE_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'UNR_G_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'GROWTH_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'GROWTH4_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'GROWTH4_US_BAR');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'BLT_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'BLT_US_BAR');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'E');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.endo_names = strvcat(M_.endo_names,'E2');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'');
M_.param_names = 'rho_us';
M_.param_names_tex = '';
M_.param_names = strvcat(M_.param_names,'rr_us_bar_ss');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'alpha_us1');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'alpha_us2');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'tau_us');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'growth_us_ss');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'beta_us1');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'beta_us2');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'beta_us3');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'lambda_us1');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'lambda_us2');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'gamma_us1');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'gamma_us2');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'gamma_us4');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'pietar_us_ss');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'alpha_us3');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'kappa_us');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names = strvcat(M_.param_names,'theta');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.exo_det_nbr = 0;
M_.exo_nbr = 11;
M_.endo_nbr = 24;
M_.recur_nbr = 0;
M_.param_nbr = 18;
M_.Sigma_e = zeros(11, 11);
M_.lead_lag_incidence = [
	 0 0 0 0 0 0 0 0 13 28 0 0 0 0;
	 0 0 0 0 0 0 0 0 14 29 0 0 0 0;
	 0 0 0 0 0 0 0 0 0 30 0 0 0 0;
	 0 0 0 0 0 0 0 0 15 31 0 0 0 0;
	 0 0 0 0 0 0 0 0 16 32 0 0 0 0;
	 0 0 0 0 0 0 9 11 17 33 52 0 0 0;
	 0 0 0 0 0 0 0 0 18 34 0 0 54 55;
	 0 0 0 0 0 0 0 0 19 35 53 0 0 56;
	 0 0 0 0 0 6 0 0 20 36 0 0 0 0;
	 0 0 0 0 0 7 0 0 21 37 0 0 0 0;
	 0 0 0 0 0 0 0 0 22 38 0 0 0 0;
	 0 0 0 0 0 0 0 0 23 39 0 0 0 0;
	 0 0 0 0 0 0 0 0 24 40 0 0 0 0;
	 0 0 0 0 0 0 0 0 0 41 0 0 0 0;
	 0 0 0 0 0 0 0 0 0 42 0 0 0 0;
	 0 0 0 0 0 0 0 0 0 43 0 0 0 0;
	 0 0 0 0 0 0 0 0 25 44 0 0 0 0;
	 0 0 0 0 0 0 0 0 0 45 0 0 0 0;
	 0 0 0 0 0 0 0 0 0 46 0 0 0 0;
	 0 0 0 0 0 0 0 0 0 47 0 0 0 0;
	 0 0 0 0 0 0 0 0 0 48 0 0 0 0;
	 0 0 0 0 0 0 0 0 26 49 0 0 0 0;
	 1 2 3 4 5 8 10 12 27 50 0 0 0 0;
	 0 0 0 0 0 0 0 0 0 51 0 0 0 0;]';
M_.exo_names_orig_ord = [1:11];
M_.maximum_lag = 9;
M_.maximum_lead = 4;
M_.maximum_endo_lag = 9;
M_.maximum_endo_lead = 4;
oo_.steady_state = zeros(24, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(11, 1);
M_.params = repmat(NaN,18, 1);
M_.params( 3 ) = 0.7796;
alpha_us1 = M_.params( 3 );
M_.params( 4 ) = 0.1874;
alpha_us2 = M_.params( 4 );
M_.params( 16 ) = 0.3352;
alpha_us3 = M_.params( 16 );
M_.params( 1 ) = 0.9;
rho_us = M_.params( 1 );
M_.params( 2 ) = 1.8456;
rr_us_bar_ss = M_.params( 2 );
M_.params( 5 ) = 0.10;
tau_us = M_.params( 5 );
M_.params( 6 ) = 2.7599;
growth_us_ss = M_.params( 6 );
M_.params( 7 ) = 0.9223;
beta_us1 = M_.params( 7 );
M_.params( 8 ) = 0.1198;
beta_us2 = M_.params( 8 );
M_.params( 9 ) = 0.1300;
beta_us3 = M_.params( 9 );
M_.params( 10 ) = 0.6380;
lambda_us1 = M_.params( 10 );
M_.params( 11 ) = 0.1948;
lambda_us2 = M_.params( 11 );
M_.params( 12 ) = 0.8318;
gamma_us1 = M_.params( 12 );
M_.params( 13 ) = 1.8091;
gamma_us2 = M_.params( 13 );
M_.params( 14 ) = 0.5332;
gamma_us4 = M_.params( 14 );
M_.params( 15 ) = 2.5;
pietar_us_ss = M_.params( 15 );
M_.params( 17 ) = 20.0890;
kappa_us = M_.params( 17 );
M_.params( 18 ) = 1;
theta = M_.params( 18 );
% 
% SHOCKS instructions 
% 
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(10, 10) = (0.4)^2;
M_.Sigma_e(11, 11) = (0.2)^2;
M_.Sigma_e(5, 5) = (0.10)^2;
M_.Sigma_e(7, 7) = (0.05)^2;
M_.Sigma_e(8, 8) = (0.7)^2;
M_.Sigma_e(1, 1) = (0.1)^2;
M_.Sigma_e(4, 4) = (0.7)^2;
M_.Sigma_e(9, 9) = (0.10)^2;
M_.Sigma_e(3, 3) = (0.10)^2;
M_.Sigma_e(2, 2) = (0.2)^2;
M_.Sigma_e(6, 6) = (0.25)^2;
M_.Sigma_e(7, 8) = 0.003500000000000001; M_.Sigma_e(8, 7) = M_.Sigma_e(7, 8);
M_.Sigma_e(6, 5) = 0.002500000000000001; M_.Sigma_e(5, 6) = M_.Sigma_e(6, 5);
options_.unit_root_vars=[];
options_.unit_root_vars = strvcat(options_.unit_root_vars,'UNR_US_BAR');
options_.unit_root_vars = strvcat(options_.unit_root_vars,'UNR_US');
options_.unit_root_vars = strvcat(options_.unit_root_vars,'LCPI_US');
options_.unit_root_vars = strvcat(options_.unit_root_vars,'LGDP_US');
options_.unit_root_vars = strvcat(options_.unit_root_vars,'LGDP_US_BAR');
options_.unit_root_vars = strvcat(options_.unit_root_vars,'BLT_US');
options_.unit_root_vars = strvcat(options_.unit_root_vars,'BLT_US_BAR');
;
steady;
check;
global estim_params_
var_list_ = [];
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_names = [];
estim_params_.user_param_names = [];
estim_params_.param_vals = [];
M_.H = 0;
estim_params_.param_vals = [estim_params_.param_vals; 3 NaN -Inf Inf 1 0.8 0.1 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 4 NaN -Inf Inf 2 0.3 0.20 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 16 NaN -Inf Inf 1 0.5 0.20 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 6 NaN -Inf Inf 3 2.5 0.25 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 2 NaN -Inf Inf 3 2.0 0.2 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 1 NaN -Inf Inf 1 0.9 0.05 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 5 NaN -Inf Inf 1 0.1 0.05 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 7 NaN -Inf Inf 2 0.75 0.10 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 8 NaN -Inf Inf 1 0.15 0.1 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 9 NaN -Inf Inf 2 0.20 0.05 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 10 NaN -Inf Inf 1 0.50 0.10 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 11 NaN -Inf Inf 2 0.25 0.05 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 12 NaN -Inf Inf 1 0.5 0.05 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 13 NaN -Inf Inf 2 1.50 0.30 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 14 NaN -Inf Inf 2 0.20 0.05 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 17 NaN -Inf Inf 2 20 0.5 NaN NaN NaN];
estim_params_.param_vals = [estim_params_.param_vals; 18 NaN -Inf Inf 2 1 0.5 NaN NaN NaN];
estim_params_.var_exo = [estim_params_.var_exo; 2 NaN -Inf Inf 4 0.2 inf NaN NaN NaN];
estim_params_.var_exo = [estim_params_.var_exo; 3 NaN -Inf Inf 4 0.1 inf NaN NaN NaN];
estim_params_.var_exo = [estim_params_.var_exo; 9 NaN -Inf Inf 4 0.10 inf NaN NaN NaN];
estim_params_.var_exo = [estim_params_.var_exo; 6 NaN -Inf Inf 4 0.25 inf NaN NaN NaN];
estim_params_.var_exo = [estim_params_.var_exo; 7 NaN -Inf Inf 4 0.05 inf NaN NaN NaN];
estim_params_.var_exo = [estim_params_.var_exo; 5 NaN -Inf Inf 4 0.10 inf NaN NaN NaN];
estim_params_.var_exo = [estim_params_.var_exo; 8 NaN -Inf Inf 4 0.7 inf NaN NaN NaN];
estim_params_.var_exo = [estim_params_.var_exo; 4 NaN -Inf Inf 4 0.7 inf NaN NaN NaN];
estim_params_.var_exo = [estim_params_.var_exo; 1 NaN -Inf Inf 4 0.2 inf NaN NaN NaN];
estim_params_.var_exo = [estim_params_.var_exo; 10 NaN -Inf Inf 4 0.4 inf NaN NaN NaN];
estim_params_.var_exo = [estim_params_.var_exo; 11 NaN -Inf Inf 4 0.2 inf NaN NaN NaN];
estim_params_.corrx = [estim_params_.corrx; 6 5 NaN -Inf Inf 1 0.25 0.1 NaN NaN NaN];
estim_params_.corrx = [estim_params_.corrx; 7 8 NaN -Inf Inf 1 0.05 0.02 NaN NaN NaN];
options_.varobs=[];
options_.varobs = strvcat(options_.varobs,'UNR_US');
options_.varobs = strvcat(options_.varobs,'RS_US');
options_.varobs = strvcat(options_.varobs,'LCPI_US');
options_.varobs = strvcat(options_.varobs,'LGDP_US');
options_.varobs = strvcat(options_.varobs,'BLT_US');
options_.trend_coeff_ = {};
tmp1 = strmatch('LCPI_US',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(15)/4';
tmp1 = strmatch('LGDP_US',options_.varobs,'exact');
options_.trend_coeffs{tmp1} = 'M_.params(6)/4';
M_.exo_names_tex = 'RES\_RR\_US\_BAR';
M_.exo_names_tex = strvcat(M_.exo_names_tex, 'RES\_UNR\_US\_GAP');
M_.exo_names_tex = strvcat(M_.exo_names_tex, 'RES\_UNR\_US\_BAR');
M_.exo_names_tex = strvcat(M_.exo_names_tex, 'RES\_RS\_US');
M_.exo_names_tex = strvcat(M_.exo_names_tex, 'RES\_G\_US');
M_.exo_names_tex = strvcat(M_.exo_names_tex, 'RES\_Y\_US');
M_.exo_names_tex = strvcat(M_.exo_names_tex, 'RES\_LGDP\_US\_BAR');
M_.exo_names_tex = strvcat(M_.exo_names_tex, 'RES\_PIE\_US');
M_.exo_names_tex = strvcat(M_.exo_names_tex, 'RES\_UNR\_G\_US');
M_.exo_names_tex = strvcat(M_.exo_names_tex, 'RES\_BLT\_US');
M_.exo_names_tex = strvcat(M_.exo_names_tex, 'RES\_BLT\_US\_BAR');
M_.endo_names_tex = 'RR\_US';
M_.endo_names_tex = strvcat(M_.endo_names_tex,'RR\_US\_BAR');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'UNR\_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'UNR\_US\_GAP');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'UNR\_US\_BAR');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'PIE\_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'PIE\_US4');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'Y\_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'LGDP\_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'LGDP\_US\_BAR');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'RS\_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'G\_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'LCPI\_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'E4\_PIE\_US4');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'E1\_Y\_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'E1\_PIE\_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'UNR\_G\_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'GROWTH\_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'GROWTH4\_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'GROWTH4\_US\_BAR');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'BLT\_US');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'BLT\_US\_BAR');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'E');
M_.endo_names_tex = strvcat(M_.endo_names_tex,'E2');
M_.param_names_tex = '\rho _{us}';
M_.param_names_tex = strvcat(M_.param_names_tex,'rr\_us\_bar\_ss');
M_.param_names_tex = strvcat(M_.param_names_tex,'\alpha _{us1}');
M_.param_names_tex = strvcat(M_.param_names_tex,'\alpha _{us2}');
M_.param_names_tex = strvcat(M_.param_names_tex,'\tau _{us}');
M_.param_names_tex = strvcat(M_.param_names_tex,'');
M_.param_names_tex = strvcat(M_.param_names_tex,'growth\_us\_ss');
M_.param_names_tex = strvcat(M_.param_names_tex,'\beta _{us1}');
M_.param_names_tex = strvcat(M_.param_names_tex,'\beta _{us2}');
M_.param_names_tex = strvcat(M_.param_names_tex,'\beta _{us3}');
M_.param_names_tex = strvcat(M_.param_names_tex,'\lambda _{us1}');
M_.param_names_tex = strvcat(M_.param_names_tex,'\lambda _{us2}');
M_.param_names_tex = strvcat(M_.param_names_tex,'\gamma _{us1}');
M_.param_names_tex = strvcat(M_.param_names_tex,'\gamma _{us2}');
M_.param_names_tex = strvcat(M_.param_names_tex,'\gamma _{us4}');
M_.param_names_tex = strvcat(M_.param_names_tex,'pietar\_us\_ss');
M_.param_names_tex = strvcat(M_.param_names_tex,'\alpha _{us3}');
M_.param_names_tex = strvcat(M_.param_names_tex,'\kappa _{us}');
M_.param_names_tex = strvcat(M_.param_names_tex,'\theta _{us}');
estim_params_.tex = '\alpha _{us}';
estim_params_.tex = strvcat(estim_params_.tex,'\alpha _{us2}');
estim_params_.tex = strvcat(estim_params_.tex,'\alpha _{us3}');
estim_params_.tex = strvcat(estim_params_.tex,'growth \_us\_ss');
estim_params_.tex = strvcat(estim_params_.tex,'rr\_us\_bar\_ss');
estim_params_.tex = strvcat(estim_params_.tex,'\rho _{us}');
estim_params_.tex = strvcat(estim_params_.tex,'\tau _{us}');
estim_params_.tex = strvcat(estim_params_.tex,'\beta _{us1}');
estim_params_.tex = strvcat(estim_params_.tex,'\beta _{us2}');
estim_params_.tex = strvcat(estim_params_.tex,'\beta _{us3}');
estim_params_.tex = strvcat(estim_params_.tex,'\lambda _{us1}');
estim_params_.tex = strvcat(estim_params_.tex,'\lambda _{us2}');
estim_params_.tex = strvcat(estim_params_.tex,'\gamma _{us1}');
estim_params_.tex = strvcat(estim_params_.tex,'\gamma _{us2}');
estim_params_.tex = strvcat(estim_params_.tex,'\gamma _{us4}');
estim_params_.tex = strvcat(estim_params_.tex,'\kappa _{us}');
estim_params_.tex = strvcat(estim_params_.tex,'\theta _{us}');
estim_params_.tex = strvcat(estim_params_.tex,'RES\_UNR\_US\_GAP');
estim_params_.tex = strvcat(estim_params_.tex,'RES\_UNR\_US\_BAR');
estim_params_.tex = strvcat(estim_params_.tex,'RES\_UNR\_G\_US');
estim_params_.tex = strvcat(estim_params_.tex,'RES\_Y\_US');
estim_params_.tex = strvcat(estim_params_.tex,'RES\_LGDP\_US\_BAR');
estim_params_.tex = strvcat(estim_params_.tex,'RES\_G\_US');
estim_params_.tex = strvcat(estim_params_.tex,'RES\_PIE\_US');
estim_params_.tex = strvcat(estim_params_.tex,'RES\_RS\_US');
estim_params_.tex = strvcat(estim_params_.tex,'RES\_RR\_US\_BAR');
estim_params_.tex = strvcat(estim_params_.tex,'RES\_BLT\_US');
estim_params_.tex = strvcat(estim_params_.tex,'RES\_BLT\_US\_BAR');
estim_params_.tex = strvcat(estim_params_.tex,'CC_RES\_Y\_US\_RES\_G\_US');
estim_params_.tex = strvcat(estim_params_.tex,'CC\_RES\_LGDP\_US\_BAR\_RES\_PIE\_US');
options_.kalman_algo = 5;
options_.conf_sig = 0.95;
options_.filter_step_ahead = [1:12];
options_.filtered_vars = 1;
options_.forecast = 12;
options_.mh_jscale = 0.35;
options_.mh_nblck = 1;
options_.mh_replic = 0;
options_.mode_compute = 0;
options_.nobs = 56;
options_.datafile = 'data';
options_.mode_file = 'soe1_mode';
var_list_=[];
var_list_ = strvcat(var_list_,'Y_US');
var_list_ = strvcat(var_list_,'PIE_US4');
var_list_ = strvcat(var_list_,'RS_US');
var_list_ = strvcat(var_list_,'UNR_US');
var_list_ = strvcat(var_list_,'UNR_US_BAR');
var_list_ = strvcat(var_list_,'GROWTH_US');
var_list_ = strvcat(var_list_,'GROWTH4_US');
var_list_ = strvcat(var_list_,'GROWTH4_US_BAR');
var_list_ = strvcat(var_list_,'BLT_US');
dynare_estimation(var_list_);
options_.order = 1;
var_list_=[];
var_list_ = strvcat(var_list_,'Y_US');
var_list_ = strvcat(var_list_,'PIE_US4');
var_list_ = strvcat(var_list_,'RS_US');
var_list_ = strvcat(var_list_,'UNR_US');
var_list_ = strvcat(var_list_,'UNR_US_BAR');
var_list_ = strvcat(var_list_,'GROWTH_US');
var_list_ = strvcat(var_list_,'GROWTH4_US');
var_list_ = strvcat(var_list_,'GROWTH4_US_BAR');
var_list_ = strvcat(var_list_,'BLT_US');
info = stoch_simul(var_list_);
data;
nobs = 56;
gl_report
firstdate = '1994Q1'; 
fcast_steps = [1 4 8 12];
max_step = max(fcast_steps);
[fy,fx,Fy,Fx,Udecomp,ndiffuse] = calc_fcast_all_4a;
save([M_.dname '_forecasts.mat'], 'fy', 'fx', 'Fy', 'Fx', 'Udecomp', 'ndiffuse');
disp(sprintf('\n'));disp('Reporting forecast errors');
report_smoothed_errors_4(fx, Fx, ndiffuse, strvcat('Y_US', 'PIE_US4', 'RS_US', 'UNR_US', 'UNR_US_BAR', 'GROWTH_US', 'GROWTH4_US', 'GROWTH4_US_BAR'), fcast_steps, firstdate);
exo_ord = [1 4 2 5 3 6 7 8 9 10];
disp('Reporting dynamic forecasts 1 period ahead');
report_fcast_dynamic_4a(fx, Fx, Udecomp, ndiffuse, 1, 1, exo_ord, firstdate,var_list_);
disp('Reporting dynamic forecasts 4 periods ahead');
report_fcast_dynamic_4a(fx, Fx, Udecomp, ndiffuse, 1, 4, exo_ord, firstdate,var_list_);
disp('Reporting dynamic forecasts 8 periods ahead');
report_fcast_dynamic_4a(fx, Fx, Udecomp, ndiffuse, 1, 8, exo_ord, firstdate,var_list_);
disp('Reporting dynamic forecasts 12 periods ahead');
report_fcast_dynamic_4a(fx, Fx, Udecomp, ndiffuse, 1, 12, exo_ord, firstdate,var_list_);
save('soe1_results', 'oo_');
diary off

disp(['Total computing time : ' sec2hms(round(toc)) ]);
