% Run mainfile.m to replicate the results. Before running mainfile.m, you need to input information on the type of the shock by changing codes in line 5. 

clear;
% input information on the type of the shock
token = 2 % equals 1 for aggregate shock, equals 2 for SOE shock, equals 3 for POE shock
save shocktype token;
%optimal_Taylor; % calculates the optimal policy coefficients that maximize social welfare

display_simple; % generate tables  using respolicy_X.mat that saves optimal policy coefficients and welfare results, generated by optimal_Taylor.m
plot_irfs4;     % generate figures using resdisplay generated by display_simple.m 

